### PR TITLE
Upgraded fast to latest version and implemented manual seed point

### PR DESCRIPTION
**Pull request by smistad**
Only tested on ubuntu 16.04

### CODE REVIEW

**Comment by jonei** [comment]
This gives errors on creating the CustusX installer on Linux and Mac. The variable ${FAST_SOURCE_DIR}
which was used to copy files into the installer in the Airways plugin is now empty. Can you look into that?

**Comment by jonei** [comment]
On Windows there is a build error for many files because of some MP flag I think. Can you look into that?
E.g.:
[shell ###] FAILED: CMakeFiles/FAST.dir/source/FAST/Algorithms/ImageResampler/ImageResampler.cpp.obj
[shell ###] MP
[shell ###] c1xx: fatal error C1083: Cannot open source file: ';/MP': No such file or directory

**Comment by smistad** [comment]
There is a ; which should not be there. Try replacing 
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}" "/MP")
with
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /MP")

in FAST/CMakeLists.txt. If that works on your system I will add the fix to FAST.

**Comment by smistad** [comment]
I have pushed a new commit to my upgrade-fast branch which should fix the ${FAST_SOURCE_DIR} issue. However since this PR has status merged, I don't think the commit will show in this PR.

**Comment by jonei** [comment]
I see you have opened a new PR.
Your suggestion fixed the first problem with the MP flag, but I got this error then:
C:\dev\cx\FAST\FAST\source\FAST\Algorithms\IterativeClosestPoint\IterativeClosestPoint.cpp(79): error C3016: 'b': index variable in OpenMP 'for' statement must have signed integral type
Setting the first looping index after the pragma to int madde it compile:
#pragma omp parallel for
    for(uint b = 0; b < B.cols(); ++b) {
==>
#pragma omp parallel for
    for(int b = 0; b < B.cols(); ++b) {

**Pull request merged**
